- name: string to number
  hosts: localhost
  vars_prompt:
  - name: num
    prompt: Please enter numberr
    private: no
  tasks:
  - name: check num is greater than 0
    ansible.builtin.debug:
     msg: "Num is {{num  < 10 }}"