- name: unique values
  hosts: localhost
  vars:
   numbers: [1,2,2,5,6,7,8,8]
  tasks:
  - name: check unique values
    ansible.builtin.debug:
      msg: "checking unique values are {{numbers | unique}}"