- name: Debug
  hosts: localhost
  become: yes
  vars:
   course: "DevOps"
   trainer: "sivakumar"
   duration: "120hr"
  tasks:
  - name: debug task
    ansible.builtin.debug:
      msg: "Hello World, checking variables course is {{course}}, trainer is {{trainer}} and duration {{duration}}"