- name: install
  hosts: web
  become: yes
  tasks:
   - name: install nginx
    #  ansible.builtin.package: # It makes to instlal in different types of distros=> like centos, ubuntu
     ansible.builtin.dnf:
      name: nginx
      state: latest
    
   - name: start service
     ansible.builtin.service:
       name: nginx
       state: started 
       enabled: yes

     